vich_uploader:
    db_driver: orm
    twig: true            # set to false to disable twig integration
    form: true
    metadata:
        type: attribute

    mappings:
        projet_images:
            uri_prefix: /assets/public/img/projets
            upload_destination: '%kernel.project_dir%/public/assets/public/img/projets'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_update: true
            delete_on_remove: true